// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzCm65rndFOoVraH5zc5G8JhwTIHQVbJA',
    appId: '1:821220114977:web:ce82710b7e8de8b6489960',
    messagingSenderId: '821220114977',
    projectId: 'simplepay-1',
    authDomain: 'simplepay-1.firebaseapp.com',
    storageBucket: 'simplepay-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi7nIlIHUKPTfB-x_LLMQe9Mi7wPuWb7w',
    appId: '1:821220114977:android:aba9ed3a1cf91479489960',
    messagingSenderId: '821220114977',
    projectId: 'simplepay-1',
    storageBucket: 'simplepay-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnccU_T2kiH4K6jApBWm92s7mmzXmDp-E',
    appId: '1:821220114977:ios:a35b7d0c57460396489960',
    messagingSenderId: '821220114977',
    projectId: 'simplepay-1',
    storageBucket: 'simplepay-1.appspot.com',
    iosBundleId: 'com.example.simplepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnccU_T2kiH4K6jApBWm92s7mmzXmDp-E',
    appId: '1:821220114977:ios:a35b7d0c57460396489960',
    messagingSenderId: '821220114977',
    projectId: 'simplepay-1',
    storageBucket: 'simplepay-1.appspot.com',
    iosBundleId: 'com.example.simplepay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzCm65rndFOoVraH5zc5G8JhwTIHQVbJA',
    appId: '1:821220114977:web:00c9ba8c6398c4d2489960',
    messagingSenderId: '821220114977',
    projectId: 'simplepay-1',
    authDomain: 'simplepay-1.firebaseapp.com',
    storageBucket: 'simplepay-1.appspot.com',
  );
}
