// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOBnpgG87IWAzziGmiNBZ1iPfyq-gDndU',
    appId: '1:894953683674:web:c9d4b2f1f15f9116d383e3',
    messagingSenderId: '894953683674',
    projectId: 'simplepay-2',
    authDomain: 'simplepay-2.firebaseapp.com',
    storageBucket: 'simplepay-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIaZv4cKkwZHXuxI-nt1-sf7QUIC9a00',
    appId: '1:894953683674:android:ae0ac9812d962aa4d383e3',
    messagingSenderId: '894953683674',
    projectId: 'simplepay-2',
    storageBucket: 'simplepay-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkfS4Hq65Vzq1D0V93gzzZ_3Vt8vfqAuI',
    appId: '1:894953683674:ios:d08cc4fbbb1f5527d383e3',
    messagingSenderId: '894953683674',
    projectId: 'simplepay-2',
    storageBucket: 'simplepay-2.appspot.com',
    iosBundleId: 'com.example.simplepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkfS4Hq65Vzq1D0V93gzzZ_3Vt8vfqAuI',
    appId: '1:894953683674:ios:d08cc4fbbb1f5527d383e3',
    messagingSenderId: '894953683674',
    projectId: 'simplepay-2',
    storageBucket: 'simplepay-2.appspot.com',
    iosBundleId: 'com.example.simplepay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOBnpgG87IWAzziGmiNBZ1iPfyq-gDndU',
    appId: '1:894953683674:web:20d1391ae1cfceffd383e3',
    messagingSenderId: '894953683674',
    projectId: 'simplepay-2',
    authDomain: 'simplepay-2.firebaseapp.com',
    storageBucket: 'simplepay-2.appspot.com',
  );

}